### ISSUE TITLE
Conteúdo dinâmico 🤘🏻

### ISSUE THREAD

**Issue by educbraga** [RamonMoraesyyz/site-brotherhood#14]
- [x] No seu vs code adicione a extensão https://marketplace.visualstudio.com/items?itemName=Nuxt.mdc
- [x] Criar um branch chamado conteudoDinamico
- [x] Confirmar que está neste branch ao invés do main
- [x] Executar npm install @nuxt/content
- [x] Adicionar @nuxt/content aos módulos do projeto no arquivo nuxt.config.ts:
<img width="340" alt="image" src="https://github.com/RamonMoraesyyz/site-brotherhood/assets/21699905/984cd613-74bd-41a2-a144-38f92d0f59d4">

- [x] Criar uma pasta chamada content
- [x] Criar uma pasta dentro de content chamada produtos
- [x] Criar nessa pasta (content/produtos/) um arquivo saison.md com qualquer frase dentro. Abaixo foi criado um arquivo index na pasta content, mas no seu caso é um arquivo saison.md na pasta content/produtos/
<img width="197" alt="image" src="https://github.com/RamonMoraesyyz/site-brotherhood/assets/21699905/35ecfcc0-77f6-4276-a349-430c44d3b194">

- [x] Na pasta pages criar um arquivo chamado [...slug].vue
<img width="200" alt="image" src="https://github.com/RamonMoraesyyz/site-brotherhood/assets/21699905/215276c9-1cf6-4e7f-ae12-deeb09ccd79b">

- [x] Acessar /produtos/saison e conferir se funcionou
- [x] Funcionando ou não, dar retorno ao @educbraga para prosseguirmos e mais passos serem adicionados aqui

A única coisa que fiz aqui foi transcrever parte dos passos que estão na documentação:
https://content.nuxt.com/get-started/installation
https://content.nuxt.com/usage/content-directory

@RamonMoraesyyz 

- [x] Nos seus arquivos markdown, coloque esta estrutura:

```
---
name: 'Nome do produto'
ibu: 'valor'
abv: 'valor%'
ebc: 'valor'
harmonization: 'Alimentos que combinam'
image: 'link da imagem'
---
texto aqui...
```

- [x] na página pages/produtos/[...slug.vue] coloque este script:

```
<script setup>
import { useRoute } from "nuxt/app";

const route = useRoute()
const product = route.params.slug

const { data: product } = await useAsyncData('produtos', () => queryContent(`/produtos/${product}`).findOne())
</script>
```

Já no template:

- [x] No seu título coloque: {{product.name}}
- [x] No seu título coloque: {{product.name}}
- [x] No campo com o IBU coloque: {{product.ibu}}
- [x] No campo com o ABV coloque: {{product.abv}}
- [x] No campo com o EBC coloque: {{product.ebc}}
- [x] No campo com as harmonizações coloque: {{product.harmonization}}
- [x] Na imagem use product.image
- [x] Onde está a descrição, coloque:
```
  <ContentRenderer :value="product" />
```

- [x] Acrescente pelo menos mais um produto.

Aqui você encontra como "puxar" os dados da sua pasta content usando o Nuxt Content: https://content.nuxt.com/composables/query-content

puxar os dados = montar uma requisição = montar uma query

Como no link, o formato é este:

```
const { data: nomeDaVariávelQueIráUsarNoTemplate } = await useAsyncData('nomeOpcionalDaRequisição', () => queryContent('emQualPastaDentroDeContentIráBuscar').oRestoDaQueryAqui)
```

por exemplo:
```
const { data: frutas } = await useAsyncData(() => queryContent('frutas').find())
```

Nesta query criamos uma variável chamada frutas. Como o nome da query é opcional, esse nome não foi colocado. Ela busca (find) todas as frutas na pasta frutas.

Indo pro código:
- [x] No seu componente BrotherNavbar adicione um <script setup></script> no arquivo.
- [x] Adicione a seguinte query para buscar todos os produtos que estão na pasta produtos:
```  
const { data: products } = await useAsyncData(() => queryContent('produtos').find())
```
Observe que ela os armazena numa variável chamada products, mas o nome da variável pode ser o que você preferir.

- [x] Acrescente temporariamente a seguinte linha para mostrar a variável products no seu console:
```
  console.log(products.value, "products");
```

- [x] Abra seu console e observe que nesta variável temos os links/urls de todos os seus produtos:
<img width="423" alt="image" src="https://github.com/RamonMoraesyyz/site-brotherhood/assets/21699905/c7d585bf-ee41-422f-b73a-6da3e72b289d">

- [x] Expanda um dos produtos e você verá os dados dele, incluindo o seu nome:
<img width="241" alt="image" src="https://github.com/RamonMoraesyyz/site-brotherhood/assets/21699905/d40bbc77-112c-4dd5-aa77-0d3585957e86">

Essas duas informações são importantes pois o UDropdown do nuxt espera um link e um nome para exibir cada item do menu:
<img width="210" alt="image" src="https://github.com/RamonMoraesyyz/site-brotherhood/assets/21699905/10980ee9-80be-4665-a6bf-3dfe68716f40">
Aqui tem um exemplo de como o componente UDropdown espera e entende:
<img width="455" alt="image" src="https://github.com/RamonMoraesyyz/site-brotherhood/assets/21699905/95e7a4c2-0d0c-4958-a193-2a35fe47c8d6">
Observe que é um array [] com outros arrays dentro, sendo um array interno para cada produto. Dentro do array de cada produto tem um objeto {} com a chave label, que contém o nome que aparece no menu e uma chave to que tem o link pra página.

Aqui tem mais detalhes sobre como o UDropdown funciona: https://ui.nuxt.com/components/dropdown

Vamos construir uma variável com os produtos que já temos, mas no formato que o UDropdown espera e entende.

Vamos entrar em cada produto (map), coletar essas duas informações, criar um array para o produto e nele colocar um objeto com o label e o to.

No "label" iremos guardar o título do produto, ou seja: name
No "to" iremos guardar a URL, ou seja: _path

Em código:

```
const itensDoMenu = products.value.map((produto, index) => {
  return [{ label: produto.name, to: produto._path }];
```

- [x] Adicione o código acima ao seu script. Observe que os itens do menu ficaram na variável itensDoMenu

Seu script deve estar assim:
```
<script setup>
  const { data: products } = await useAsyncData(() => queryContent('produtos').find())

  const itensDoMenu = products.value.map((produto, index) => {
  return [{ label: produto.name, to: produto._path }];
});
</script>
```

- [x] Para passarmos essa informação para o UDropdown, basta colocar o seguinte nele:
```
:items="itensDoMenu"
```
Ele ficará assim:

```
<UDropdown :items="itensDoMenu" :popper="{ placement: 'bottom-start' }">
```

Feito isto você tem um menu funcional. 🍺🤘🏻
<img width="251" alt="image" src="https://github.com/RamonMoraesyyz/site-brotherhood/assets/21699905/aff4b416-b45e-4da9-8288-ac58314d7f67">

- [x] Pronto!

**Comment by educbraga** [comment]
- [ ] Nos seus arquivos markdown, coloque esta estrutura:

`
---
name: 'Nome do produto'
ibu: 'valor'
abv: 'valor%'
ebc: 'valor'
harmonization: 'Alimentos que combinam'
image: 'link da imagem'
---
texto aqui...
`

- [ ] na página pages/produtos/[...slug.vue] coloque este script:

`
<script setup>
import { useRoute } from "nuxt/app";

const route = useRoute()
const product = route.params.slug

const { data } = await useAsyncData('produtos', () => queryContent(`/produtos/${product}`).findOne())
</script>
`

Já no template:

- [ ] No seu título coloque: {{product.name}}
- [ ] No seu título coloque: {{product.name}}
- [ ] No campo com o IBU coloque: {{product.ibu}}
- [ ] No campo com o ABV coloque: {{product.abv}}
- [ ] No campo com o EBC coloque: {{product.ebc}}
- [ ] No campo com as harmonizações coloque: {{product.harmonization}}
- [ ] Na imagem use product.image
- [ ] Onde está a descrição, coloque:
`
  <ContentRenderer :value="data" />
`

- [ ] Acrescente pelo menos mais um produto.

**Comment by RamonMoraesyyz** [comment]
@educbraga, adicionei 7 produtos.
