### ISSUE TITLE
Página inicial

### ISSUE THREAD

**Issue by educbraga** [RamonMoraesyyz/site-brotherhood#4]
- [x]  Baixar imagem da marca no figma
- [x] ![Inicial](https://github.com/RamonMoraesyyz/site-brotherhood/assets/21699905/9ccb6dc8-4a79-4f23-b749-a450fe4f52dc)
- [x]  Usar este vídeo no fundo com autoplay: https://www.youtube.com/watch?v=9BnCP8OUpEI

**Comment by educbraga** [comment]
@RamonMoraesyyz 🚀

**Comment by RamonMoraesyyz** [comment]
Mano, fiquei com uma dúvida, é pra construir a página toda com o vídeo em autoplay de fundo igual o modelo, certo?
Baixando a imagem no Figma (feito), e o vídeo eu baixei ele em HD na minha máquina.

**Comment by educbraga** [comment]
Exatamente isso, mano! 

Para o vídeo você pode experimentar usar o embed/incorporar do YouTube:
<img width="577" alt="image" src="https://github.com/RamonMoraesyyz/site-brotherhood/assets/21699905/302a4ff1-94ea-4068-97e5-e96326ef8758">

**Comment by educbraga** [comment]
@RamonMoraesyyz Sim. Isso aí. Olha aqui: https://daily-dev-tips.com/posts/tailwind-css-full-screen-video-header/

**Comment by RamonMoraesyyz** [comment]
Legal! Sobre a transição para a página index.vue aparecer na localhost eu consegui fazer. Apaguei a app.vue e criei a pasta pages e o arquivo index.vue.

O que estou apanhando é em "puxar" o Tailwind pro projeto, como você comentou que ele vem embutido no nuxtui, achei que era só colocar as propriedades de Tailwind que já iria aparecer na página, mas não está puxando, kkkk.

**Comment by educbraga** [comment]
interessante, mano!! Pode fazer o commit para eu verificar? @RamonMoraesyyz
