### ISSUE TITLE
Página de contato

### ISSUE THREAD

**Issue by educbraga** [RamonMoraesyyz/site-brotherhood#5]
- [x] Montar o layout abaixo apenas visualmente, usando qualquer imagem no lugar do mapa
![Contato](https://github.com/RamonMoraesyyz/site-brotherhood/assets/21699905/21898f77-5590-4b3e-b424-199fe100dab6)
- [x] Perguntar @educbraga sobre como você poderá direcionar os contatos para seu para seu e-mail e como pode adicionar o mapa

**Comment by RamonMoraesyyz** [comment]
Tarefas realizadas, página e contato criada porém sem link atrelado a index.
